name: transfer_window_simulation

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: transfer_window_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - INTERNAL_API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: transfer_window_api
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    volumes:
      - ./backend:/app
    restart: unless-stopped
